version: "3.8"

services:
  db:
    image: postgres:11.13-bullseye
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      