version: "3.8"

services:
  db:
    image: postgres:11.13-bullseye
    container_name: app_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
  ee:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_ee
    ports:
      - 18080:8080
      - 9990:9990
  ci:
    image: maven:3.8.4-jdk-8
    container_name: app_ci
