apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: buildpacks-node-tutorial
build:
  artifacts:
  - image: skaffold-build-sample
    context: app
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  local:
    tryImportMissing: true
manifests:
  rawYaml:
  - k8s/headlessService.yaml
