apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "hello World!"
