apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
        sidecar.istio.io/inject: "true"
    spec:
      restartPolicy: Always
      serviceAccountName: cicd-user
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: curl
        image: local/curl:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "sleep 100000"]
---
apiVersion: v1
kind: Service
metadata:
  name: curl-service
  namespace: cicd
spec:
  ports:
  - protocol: "TCP"
    port: 12000
    targetPort: 12000
  selector:
    app: curl
