apiVersion: batch/v1
kind: Job
metadata:
  name: lookup
spec:
  template:
    spec:
      containers:
      - name: lookup
        image: tutum/dnsutils:latest
        command: ["/bin/sh", "-c", "nslookup sample-headless | grep Address | tail -n +2 | cut -f2 -d ' '"]
      restartPolicy: Never
  backoffLimit: 4
