apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-deployment
  namespace: sample
  labels:
    app: wildfly
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wildfly
  template:
    metadata:
      labels:
        app: wildfly
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: wildfly
        image: wildfly-ee8/sample:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wildfly-service
spec:
  selector:
    app: wildfly
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
