apiVersion: apps/v1
kind: Deployment
metadata:
  name: nslookup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nslookup
  template:
    metadata:
      labels:
        app: nslookup
        sidecar.istio.io/inject: "true"
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: nslookup
        image: local/curl:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "sleep 100000"]
