apiVersion: apps/v1
kind: Deployment
metadata:
  name: random
spec:
  replicas: 6
  selector:
    matchLabels:
      app: random
  template:
    metadata:
      labels:
        app: random
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: random
        image: random:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 88
        volumeMounts:
        - name: log-volume
          mountPath: /opt/entry/logs
      volumes:
      - name: log-volume
        hostPath: 
          path: /run/desktop/mnt/host/c/mydata
