apiVersion: apps/v1
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#deploymentspec-v1-apps
kind: Deployment
metadata:
  name: wildfly-deployment
  labels:
    app: ee
spec:
  progressDeadlineSeconds: 60
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: ee
  template:
    metadata:
      labels:
        app: ee
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
