apiVersion: apps/v1
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#deploymentspec-v1-apps
kind: Deployment
metadata:
  name: wildfly-deployment
  labels:
    app: ee
spec:
  progressDeadlineSeconds: 60
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: ee
  template:
    metadata:
      labels:
        app: ee
    spec:
      containers:
      - name: sample-pod
        image: wildfly-ee8/sample:0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: "/opt/jboss/wildfly/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: game-demo
