FROM openjdk:17.0.2-jdk-bullseye

LABEL io.buildpacks.stack.id="io.github.future-architect.samples.debian"

COPY ./startup.sh /opt/jboss/wildfly/

ADD ./wildfly-27.0.1.Final.tar.gz /opt/jboss/wildfly/
