apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-manifest
  namespace: pvc-sample
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
  storageClassName: slow
status:

