apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-manifest
  namespace: pvc-sample
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests: 
      storage: 1Gi
  storageClassName: slow
