apiVersion: v1
kind: Service
metadata:
  name: roundrobin-service
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundrobin-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      restartPolicy: Always
      containers:
      - name: server
        image: wildfly-ee8/sample:0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundrobin-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      restartPolicy: Always
      containers:
      - name: client
        image: wildfly-ee8/sample:0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

