apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-disruption-budget
  annotations:
    com.example/owner: "Container A"
  labels:
    app: demo
  namespace: demo
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: application
