apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  annotations:
    com.example/owner: "Container A"
  labels:
    app: demo
  namespace: demo
data:
  application.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
