apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  annotations:
    com.example/owner: "Container A"
  labels:
    app: demo
  namespace: demo
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: db-pod
        image: db-ee8/sample:0.0
        imagePullPolicy: Never
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_DB
          value: postgres
