apiVersion: v1
kind: Service
metadata:
  name: db
  annotations:
    com.example/owner: "Container A"
  labels:
    app: demo
  namespace: demo
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
