apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limit
  annotations:
    com.example/owner: "Container A"
  labels:
    app: demo
  namespace: demo
spec:
  limits:
  - max:
      cpu: "2000m"
      memory: 2Gi
    min:
      cpu: "100m"
      memory: 100Mi
    type: Container
